### ISSUE TITLE
[subnet-visualizer] Scroller should remember last page

### ISSUE THREAD

**Issue by nemesifier** [openwisp/django-ipam#100]
Use case:

- create a big ipv6 subnet
- scroll down a few pages
- add a new ip address and watch how the page is reloaded

Ideal behaviour: the scroller reloads the last page that was shown before the add action

Actual behaviour: first page is shown.

The code which reloads the page is: https://github.com/openwisp/django-ipam/blob/master/django_ipam/static/django-ipam/js/custom.js#L6

Maybe instead of reloading the entire page we can reload just the subnet hosts being shown at that moment, but the visualizer needs to be smart enough to reload the page which is being viewed.

CC: @pawelplsi

**Comment by iharshit009** [comment]
Hi @nemesisdesign I would like to work on this issue.

**Comment by atb00ker** [comment]
@iharshit009 feel free to take any issue that someone is not working on, you don't need to ask for permissions for the same? :smile:
