### ISSUE TITLE
[subnet-visualizer] Allow to click on used ip to change them

### ISSUE THREAD

**Issue by nemesifier** [openwisp/django-ipam#101]
The new subnet visualizer allows adding IP to a subnet but not changing existing ones.

We should change it to allow this.

CC: @pawelplsi

**Comment by nepython** [comment]
@nemesisdesign @pawelplsi 
Shall I take this issue, I will try to complete it asap.:relaxed:

**Comment by nemesifier** [comment]
:+1:
