### ISSUE TITLE
[subnet-visualizer] Subnet freespace diagram disappears for slave subnets

### ISSUE THREAD

**Issue by lehone-hp** [openwisp/django-ipam#105]
How to replicate this issue.
- Create a new subnet by leaving the Master Subnet field empty.
- Open the newly created subnet and scroll down. The freespace diagram gets displayed. 
![Screenshot from 2020-03-17 17-16-30](https://user-images.githubusercontent.com/23194068/76877265-6c8e1500-6873-11ea-90d5-07075d7a7a12.png)
- Now create a slave subnet by setting the previously created subnet as the Master Subnet. 

When either master or slave subnet is opened, their respective freespace diagrams do not get displayed. Also, the **Network Hierarchical View** does not get rendered properly.

**Comment by lehone-hp** [comment]
@nemesisdesign please I will like to work on this.

**Comment by nemesifier** [comment]
What do you mean with "Network Hierarchical View does not get rendered properly"?

When I open a subnet who has a master subnet, I see a javascript error in the console:

```
Uncaught TypeError: Cannot read property 'appendChild' of null
```

Maybe that's the cause which is triggering this?
This needs to be solved for sure and you can proceed with solving that.

@atb00ker this sounds like a bug, do you know if there was any intention in hiding something on subnets who have a master subnet?

**Comment by lehone-hp** [comment]
@nemesisdesign I mean the subnet tree does not all the branches. It displays just the root node. I think this also has to do with the 

`Uncaught TypeError: Cannot read property 'appendChild' of null
`

**Comment by nemesifier** [comment]
@lehone-hp you can go ahead and fix that JS error

**Comment by atb00ker** [comment]
@nemesisdesign Yes, it looks like a bug and most probably, a new one, last I checked this thing was working and it should be related to the JS error you pointed out! :smile:
