### ISSUE TITLE
[models] Owner field

### ISSUE THREAD

**Issue by nemesifier** [openwisp/django-ipam#26]
This is another field we have added but we are not using in the code nor we are planning to use it right now.

I don't like this sort of dead useless code, imagine other people will come after us to maintain this project, they will think: what does this thing do? Can I use it somehow? Should I remove it? Should I reimplement it?

I think that we should either define what's the purpose of this or remove it.

@hispanico @anurag-ks

**Comment by anurag-ks** [comment]
I think we can reimplement this field later on, as we are not using it specifically anywhere else, in my latest PR #25, I have removed the field.
