### ISSUE TITLE
Handle invalid IPv4 or IPv6

### ISSUE THREAD

**Issue by hispanico** [openwisp/django-ipam#28]
If I try to add an invalid IPv4 or IPv6 subnet/IPaddrress, I got this error:
![image](https://user-images.githubusercontent.com/3329032/42277521-e97b3640-7f97-11e8-8748-9423d9e9d6ae.png)

Should be handled and return an error message like "Invalid IP address"

**Comment by nemesifier** [comment]
@anurag-ks I confirm this happens but only when adding a new ip address, changing an existing address works as expected.

**Comment by anurag-ks** [comment]
This is weird, the default validations are not getting called before the custom validations that were made for these models, I have added an `if` condition in the following PR - #27 which fixes this error. @nemesisdesign do review it as well.

**Comment by nemesifier** [comment]
@anurag-ks please don't mix things up or you will confuse me.
Create a separate patch for this issue with a failing test that replicates the issue and the fix.
