### ISSUE TITLE
Refactor test cases to support custom models

### ISSUE THREAD

**Issue by anurag-ks** [openwisp/django-ipam#48]
While extending [openwisp-ipam](https://github.com/openwisp/openwisp-ipam), I added `OrgMixin` from the `openwisp-users`, which basically adds an organization field to the Subnet and IpAddress tables. The test cases which involved data creation are failing as the `organization` field is required.

**Comment by nemesifier** [comment]
@anurag-ks remember all those `_create_<model-name>` method I made you write? You can now extend those and pass the organization there, see how it's done in openwisp-controller: https://github.com/openwisp/openwisp-controller/blob/master/openwisp_controller/config/tests/__init__.py#L17-L22

This will most likely need some modifications to the django-ipam test suite, Rohith has done something similar.

PS: do something like this as well please: https://github.com/openwisp/openwisp-controller/blob/master/openwisp_controller/tests/test_users_integration.py
