### ISSUE TITLE
[qa] Avoid leaving test files after tests

### ISSUE THREAD

**Issue by nemesifier** [openwisp/django-ipam#59]
**Reserved for GCI**

After running tests a test csv file is left on the filesystem.

- configure the `settings.py` test environment so that media files are uploaded to `./tests/media/`
- add `./tests/media/*` to `.gitignore`
- make sure `./tests/media/` is cleaned up during `tearDown`

**Comment by cking100** [comment]
@nemesisdesign could you please elaborate the 3rd point and what do you mean by teardown?

**Comment by nemesifier** [comment]
@cking100 https://docs.python.org/3/library/unittest.html#unittest.TestCase.tearDown
