### ISSUE TITLE
[models] Subnet.__str__ should return also subnet name

### ISSUE THREAD

**Issue by nemesifier** [openwisp/django-ipam#74]
`Subnet.__str__` should return also subnet name.

**Comment by NoumbissiValere** [comment]
yes good idea. since a human will more likely read and remember a name than an IP address. will look on this issue

**Comment by jeffysam6** [comment]
can i take up this issue?

**Comment by atb00ker** [comment]
Hello @jeffysam6 , looks like a pull request is already open for this one.

@NoumbissiValere can you please mark your pull request with this issue number so that other developers can know about it. 
Thanks! :smile:
