### ISSUE TITLE
[django] Add support for django 2.2

### ISSUE THREAD

**Issue by nemesifier** [openwisp/django-ipam#78]
Add support for django 2.2

**Comment by DaffyTheDuck** [comment]
Hello ! is anyone working on this issue ?

**Comment by atb00ker** [comment]
No, but I think it's an easy issue and I should add it for GCI, what do you think? :smile:

**Comment by DaffyTheDuck** [comment]
> No, but I think it's an easy issue and I should add it for GCI, what do you think? 😄

Yeah, Just Like Dropping Support Of Python2 😄

**Comment by DaffyTheDuck** [comment]
> No, but I think it's an easy issue and I should add it for GCI, what do you think? 😄

I Was Thinking About That As Well 😄

**Comment by DaffyTheDuck** [comment]
Hello! 
https://github.com/IAmAMissingColon/django-ipam/commit/732d62c082a63bd7855960b7ddb8957fa334cb1a

Am I doing right ?
