### ISSUE TITLE
[requirements] Update dependencies

### ISSUE THREAD

**Issue by atb00ker** [openwisp/django-ipam#79]
We need to update all the dependencies including update to django 3.0

**Comment by IAmAMissingColon** [comment]
Can I Work On This Issue ??? 😁

**Comment by someshkar** [comment]
Is this issue still open/can I work on it?

**Comment by nemesifier** [comment]
@someshkar there should be GCI tasks for this or other similar ones, look for it in the GCI system.

**Comment by strang1ato** [comment]
@someshkar Are you working on this?

**Comment by pawelplsi** [comment]
Nobody claimed it on GCI dashboard yet, so now I am working on it :smile:

**Comment by pawelplsi** [comment]
@atb00ker Should this module support Python2? There's no README entry for it and no travis CI test, but in some other places it's said that it's supported.
And what with django? There's still 1.11 there, in other modules we've droppped everything <2.2, should drop it there as well?

**Comment by nemesifier** [comment]
No, python 3 only, django 2.2 and django 3.0.
