### ISSUE TITLE
[bug] Javascript error on add subnet page

### ISSUE THREAD

**Issue by atb00ker** [openwisp/django-ipam#85]
I am seeing `Uncaught SyntaxError: Unexpected token ','` on my browser console on the add new subnet page.

**Comment by nemesifier** [comment]
@atb00ker is this still happening with the latest master?

**Comment by atb00ker** [comment]
@nemesisdesign yes it's there. 
The "values" & "label" in data is not getting a value.
```
    vals[1] = Number(vals[1]);
    data = [
      {
        values: ,
        labels: ,
        text: vals,
```

**Comment by atb00ker** [comment]
I see this is fixed by #89 but a new error shows: 
```
Uncaught TypeError: Cannot read property 'appendChild' of null
    at (index):403 - parent_element.appendChild(subnet_list);
```
Possibly this was hidden because of the previous error! :smile:

**Comment by nepython** [comment]
@atb00ker, has this issue been resolved?
> Uncaught TypeError: Cannot read property 'appendChild' of null
>     at (index):403 - parent_element.appendChild(subnet_list);
>
I tried to reproduce the errors, but was unable to do so:
![image](https://user-images.githubusercontent.com/54471024/75562372-77bd0480-5a6e-11ea-9015-302a8bbd1932.png)

![image](https://user-images.githubusercontent.com/54471024/75561768-8c4ccd00-5a6d-11ea-85e1-6f95ab3937e5.png)

Though few warnings and errors were raised as can be seen, they were specific to Mozilla Firefox and the console on Chrome showed none of these warnings/errors.
If anything else is needed to perform to reproduce the error please specify.:smile:

**Comment by atb00ker** [comment]
@nepython there have been a lot of fixes lately, if you don't see it, it's possible fixed in another commit recently.
I'll double check and close it if it's not required! :smile:

**Comment by atb00ker** [comment]
Thanks for checking @nepython , I think it got fixed during GCI but the GCI student forgot to tag this issue number in the commit hence it's not closed! :smile:

**Comment by nemesifier** [comment]
thx for updating!
