### ISSUE TITLE
[subnet-visualizer] Invalid HTML

### ISSUE THREAD

**Issue by nemesifier** [openwisp/django-ipam#96]
In the infinite scrolling subnet visualizer, I noticed that a `<div>` is used to load pages, but that `<div>` is inside a `<ul>` element, which makes it not valid HTML. We should change the structure of the HTML so that it's valid.

We can use something like `<section>` > `<div>` > `<a>` (instead of `<ul>` > `<div>` > `<li><a>`.

CC: @pawelplsi

**Comment by nepython** [comment]
@nemesisdesign , I checked the templates but found the `<ul>`  within `<div>` and not viceversa at [changeform.html](https://github.com/openwisp/django-ipam/blob/master/django_ipam/templates/admin/django-ipam/subnet/change_form.html#L36). It maybe that I am viewing the wrong template, if so can you please tell me the correct one :)

**Comment by pawelplsi** [comment]
@nepython It's not in a template, these divs are added dynamicaly by a script.
Anyway, I am working on solving it right now.
